#Turns ON Back Irrigation if no other zones are turned ON
#My 24V 500mA can only safely power one value at a time
#Set start times in the trigger sections
#and the ON time in the delay section
#Note that the start time must be staggered to meet conditions
  - alias: 'Back Irrigation'
# This can be set to "off" to prevent automation coming back ON after a reboot
# caused by a power outage
    initial_state: false
    trigger:
# "-" needed only for multiple triggers/conditions/services
    - platform: time
      after: '07:00:00'
    - platform: time
      after: '19:00:00'
    condition:
# These conditions not really needed since the hardware was 
# modified to only allow one relay ON at a time.
# If a command is received to turn one relay ON the others
# are turned OFF.
      condition: and
      conditions:
        - condition: state
          entity_id: switch.deck_irrigation
          state: 'off'
        - condition: state
          entity_id: switch.front_irrigation
          state: 'off'
#Copy this to Front Irrigation when not using cold frame
# float is needed to convert string state to float for comparison
        - condition: template
          value_template: '{{ states.sensor.yesterday_rainfall.state | float < 5 }}'
    action:
      - service: switch.turn_on
        entity_id: switch.back_irrigation
      - delay: '00:10:00'
      - service: switch.turn_off
        entity_id: switch.back_irrigation

  - alias: 'Front Irrigation'
# On reboot after a power outage restart this automation
    initial_state: true
    trigger:
    - platform: time
      after: '07:15:00'
#Removed second trigger for cold frame
    # - platform: time
      # after: '19:15:00'
    condition: 
      condition: and
      conditions:
        - condition: state
          entity_id: switch.deck_irrigation
          state: 'off'
        - condition: state
          entity_id: switch.back_irrigation
          state: 'off'
    action:
      - service: switch.turn_on
        entity_id: switch.front_irrigation
      - delay: '00:10:00'
      - service: switch.turn_off
        entity_id: switch.front_irrigation  
        
  - alias: 'Deck Irrigation'
    initial_state: false
    trigger:
    - platform: time
      after: '07:30:00'
    - platform: time
      after: '19:30:00'
    condition: 
      condition: and
      conditions:
        - condition: state
          entity_id: switch.back_irrigation
          state: 'off'
        - condition: state
          entity_id: switch.front_irrigation
          state: 'off'
    action:
      - service: switch.turn_on
        entity_id: switch.deck_irrigation
      - delay: '00:10:00'
      - service: switch.turn_off
        entity_id: switch.deck_irrigation
        
  - alias: 'Irrigation Safety'
# In case some interruption occurs while a zone is ON
# Not sure this is neccessary but does not hurt to include
# Time are after the last zone cycle
    initial_state: true
    trigger:
    - platform: time
      after: '08:00:00'
    - platform: time
      after: '20:00:00'
    action:
      - service: homeassistant.turn_off
        entity_id: group.irrigation_switches
        
# Turn ON on hour before sunset      
  - alias: 'Living Room Light ON'
    initial_state: true
    trigger:
      platform: sun
      event: sunset
      offset: "-01:00:00"
    action:
      service: switch.turn_on
      entity_id: switch.leviton_unknown_type1d04_id0334_switch_2_0

# Turn OFF at 23:30
  - alias: 'Living Room Light OFF'
    initial_state: true
    trigger:
      platform: time
      after: '23:30:00'    
    action:
      service: switch.turn_off
      entity_id: switch.leviton_unknown_type1d04_id0334_switch_2_0

  - alias: Notify iOS App Joyce
    trigger:
      platform: state
      entity_id: sensor.back_lock_last_action
      state: 'Unlocked: Joyce'
    action:
      service: notify.ios_grahams_iphone
      data:
        message: "Joyce Unlocked Door"
        
  - alias: Notify iOS App Oliver
    trigger:
      platform: state
      entity_id: sensor.back_lock_last_action
      state: 'Unlocked: Oliver'
    action:
      service: notify.ios_grahams_iphone
      data:
        message: "Oliver Unlocked Door"

# Change thermostat set point to 21 C at 7:00 but only if home and not on vacation
  - alias: Furnace ON
    trigger:
      platform: time
      after: '07:00:00'
    condition: 
      condition: and
      conditions:
        - condition: state
          entity_id: sensor.my_presence
          state: 'home'
        - condition: state
          entity_id: input_boolean.vacation
          state: 'off'    
    action:
      service: climate.set_temperature
      data_template:
        entity_id: climate.house
        temperature: !secret temperature_home
        
  - alias: Furnace OFF
    trigger:
      platform: time
      after: '23:00:00'
    action:
      service: climate.set_temperature
      data_template:
        entity_id: climate.house
        temperature: !secret temperature_away   
        
# Turn furnace OFF if its has been ON 7 minutes and the temperature is above the set point 
# Needs to be tested       
  - alias: Furnace Safety
    trigger:
      platform: state
      entity_id: switch.furnace
      state: 'on'
      for:
        minutes: 7
    condition:
      condition: template
      value_template: '{{ states.climate.house.attributes.current_temperature | float > states.climate.house.attributes.temperature | float }}'
    action:
      service: switch.turn_off
      entity_id: switch.furnace
      
# Turn temperature setpoint down if away
  - alias: Away
    trigger:
      platform: state
      entity_id: sensor.my_presence
      state: 'Away'
    action:
      service: climate.set_temperature
      data_template:
        entity_id: climate.house
        temperature: !secret temperature_away   

# Return temperature setpoint when return between 7:00 and 23:00 if not on vacation
  - alias: Home
    trigger:
      platform: state
      entity_id: sensor.my_presence
      state: 'Home'
    condition: 
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.vacation
          state: 'off'
        - condition: time
          after: '07:00:00'
          before: '23:00:00'
    action:
      service: climate.set_temperature
      data_template:
        entity_id: climate.house
        temperature: !secret temperature_home   

        
