# Command Switches
switch:
  name: aeotec_zstick_disco_light
  command_on: 'echo -e -n "\x01\x08\x00\xF2\x51\x01\x01\x05\x01\x50" > /dev/serial/by-id/usb-0658_0200-if00'
  command_off: 'echo -e -n "\x01\x08\x00\xF2\x51\x01\x00\x05\x01\x51" > /dev/serial/by-id/usb-0658_0200-if00'
# Command Sensor
sensor:
  name: Predicted Rainfall
  unit_of_measurement: "mm"
  scan_interval: 3600 
  command: >-
    python3 -c "import requests; 
    print(requests.get('https://api.open-meteo.com/v1/forecast?latitude=49.27&longitude=-122.95&daily=rain_sum&past_days=1&forecast_days=1&timezone=America%2FLos_Angeles').json()['daily']['rain_sum'][1])"
