homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone

#Show links to resources in log and frontend

#introduction:

#This start the MQTT server on Raspberry setup using the HA install script
#To access from an Arduino deviceI had to use the IP address for the Raspberry
mqtt:
  broker: localhost 
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: gbsmith
  password: mos123
  protocol: 3.1 

switch:

  - platform: mqtt
    name: "Back Irrigation"
    state_topic: "/house/switchConfirm1/"
    command_topic: "/house/switch1/"
    payload_on: "1"
    payload_off: "0"
    qos: 0
    retain: true   

  - platform: mqtt
    name: "Front Irrigation"
    state_topic: "/house/switchConfirm2/"
    command_topic: "/house/switch2/"
    payload_on: "1"
    payload_off: "0"
    qos: 0
    retain: true    

  - platform: mqtt
    name: "Deck Irrigation"
    state_topic: "/house/switchConfirm3/"
    command_topic: "/house/switch3/"
    payload_on: "1"
    payload_off: "0"
    qos: 0
    retain: true    
  

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:
# Weather Prediction

#Needed for Developer panel
group: !include groups.yaml

# switch:
  # - platform: mqtt
    # name: "Relay 1"
    # command_topic: "home/irrigation/relay1"
    # payload_on: "ON"
    # payload_off: "OFF"
  # # - platform: mqtt
    # # name: "Relay 1"
    # # state_topic: "home/irrigation/relay1"
    # # command_topic: "home/irrigation/relay1"
    # # qos: 0
    # # payload_on: "ON"
    # # payload_off: "OFF"
    # # optimistic: false 
    # # retain: true
    
  # - platform: mqtt
    # name: "Relay 2"
    # command_topic: "home/irrigation/relay2"
    # payload_on: "ON"
    # payload_off: "OFF"
  # # - platform: mqtt
    # # command_topic: "home/irrigation/relay3/set"
  # # - platform: mqtt
    # # command_topic: "home/irrigation/relay4/set"


