homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  customize: !include customize.yaml
    
#Show links to resources in log and frontend
#introduction:

http:
  api_password: !secret api_password
#This works for https://gb53smith.duckdns.org from an external network
#but not from my internal network.  Will work on chrome
  ssl_certificate: /etc/letsencrypt/live/gb53smith.duckdns.org/fullchain.pem
  ssl_key: /etc/letsencrypt/live/gb53smith.duckdns.org/privkey.pem
  base_url: gb53smith.duckdns.org

#This start the MQTT server on Raspberry setup using the HA install script
#To access from an Arduino deviceI had to use the IP address for the Raspberry
mqtt:
  broker: localhost 
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: gbsmith
  password: mos123
  protocol: 3.1 
  
zwave:
  usb_path: /dev/ttyACM0
  config_path: /home/homeassistant/.homeassistant/ozw_config

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# View all events in a logbook
logbook:

# Keep database from growing too large by purging
recorder:
  purge_days: 30
 
# Enables support for tracking state changes over time.
# Exclude those domains and entities that do not change much 
history:
  exclude:
    domains:
      - automation
      - script
    entities:
      - binary_sensor.away
      - device_tracker.grahams_iphone
      - group.zwave_components
      - group.all_switches
      - group.irrigation
      - group.irrigation_switches
      - group.living_room_light
      - group.back_door_lock
      - group.switches_off_at_restart
      - group.multisensor
      - group.multisensor_components
      - input_boolean.vacation
      - sensor.schlage_be469nxcen_touchscreen_deadbolt_access_control_4_9
      - sensor.schlage_be469nxcen_touchscreen_deadbolt_alarm_level_4_1
      - sensor.schlage_be469nxcen_touchscreen_deadbolt_alarm_type_4_0
      - sensor.schlage_be469nxcen_touchscreen_deadbolt_burglar_4_10
      - sensor.schlage_be469nxcen_touchscreen_deadbolt_power_management_4_11
      - sensor.schlage_be469nxcen_touchscreen_deadbolt_sourcenodeid_4_2
      - sensor.schlage_be469nxcen_touchscreen_deadbolt_system_4_12
      - sensor.grahams_iphone_battery_level
      - sensor.grahams_iphone_battery_state
      - sensor.joyce_ipad_battery_level
      - sensor.joyce_ipad_battery_state
      - sensor.lock_battery
      - sensor.ssl_cert_expiry
      - sensor.yesterday_rainfall
      - sensor.motion
      - sensor.rgb_state
      - sun.sun
      - switch.heat0
      - switch.heat1
      - zwave.aeotec_zw090_zstick_gen5_1
      - zwave.schlage_be469nxcen_touchscreen_deadbolt_4
      - zwave.leviton_dzr151lz_binary_scene_switch_7
  
#Send notifications to the iOS app on my iPhone
ios:
  
# Track the sun
sun:

# Experimental replacement for dumb thermostat
# Keep alive repeats furnace ON or OFF message every 3 minutes
# Furnace Arduino will expect repeated furnace ON messages to keep the furnace relay ON.

climate:
  - platform: generic_thermostat
    name: House
    heater: switch.furnace
    target_sensor: sensor.temperature
    min_temp: 15
    max_temp: 25
    target_temp: !secret temperature_home
    tolerance: 0.3
    min_cycle_duration:
      seconds: 10
    keep_alive:
      minutes: 3

# Used in automations to detect when I leave and come home again.  'on' = away
binary_sensor:
  - platform: template
    sensors:
      away:
        value_template: '{{ is_state("sensor.back_lock_last_action", "Locked: Outside Keypad")}}'
        friendly_name: 'I am away' 

input_boolean:
  vacation:
    name: "ON Vacation"
    initial: off
    icon: mdi:car
    
# Send notification if Home Assistant restarts after 10 minutes
# to wait for internet to come back up. I get an error if this is in the automation.yaml file
automation 2:
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: group.switches_off_at_restart
    - delay:
        minutes: 10
    - service: notify.ios_grahams_iphone
      data:
        message: "HA Restarted"
          
    
# Include other files to better organize code
group: !include groups.yaml
automation: !include automation.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
script: !include scripts.yaml
