homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  customize: !include customize.yaml

#Show links to resources in log and frontend
#introduction:
system_health:
#Uncomment to use ui-lovelace.yaml instead of UI
# lovelace:
  # mode: yaml

http:
  # Comment out next three lines to use NGINX
  # ssl_certificate: /ssl/fullchain.pem
  # ssl_key: /ssl/privkey.pem
  # ssl_profile: intermediate
  base_url: !secret base_url
  # ip_ban_enabled: true
  # login_attempts_threshold: 5
  
mysensors:
  gateways:
    - device: mqtt
      persistence_file: '/config/mysensors1.json'
      topic_in_prefix: 'mygateway1-out'
      topic_out_prefix: 'mygateway1-in'
  optimistic: false
  persistence: true
  retain: true
  version: '2.3'

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_key
  polling_interval: 30000
  device_config:
    light.ge_12724_3way_dimmer_switch_level: # Added to keep HA in sync after manual override
      refresh_value: true #refresh the brightness value if the dimmer do "soft off"
      delay: 2 #Amount of seconds before the refresh is done after the actual action.
      polling_intensity: 1 #Polls the device when each (polling_intensity) polling is performed by polling_interval

# Enables the frontend
frontend:
  #javascript_version: es5

# Enables configuration UI
config:

# Checks for available updates
updater:

#Replace discovery with hassio
hassio:
# Discover some devices automatically
discovery:
  ignore:
    - apple_tv
    - igd

python_script:

#Need this only to debug python scripts
# logger:
  # default: info
  # logs:
    # homeassistant.components.python_scripts: debug
    # homeassistant.components.sensor.time: error
    
# #For Mysensors debug only
# logger:
  # default: info
  # logs:
    # homeassistant.components.mysensors: debug
    # mysensors: debug
    
#Enable IOS App, Home Assistant Companion
mobile_app:

# Send SMS if burgular alarm triggered
twilio:
  account_sid: !secret account_sid
  auth_token: !secret auth_token

notify:
  - name: Burglar Alarm SMS
    platform: twilio_sms
    from_number: !secret from_number
  - name: energy_notify
    platform: file
    filename: hourly_energy.csv
    timestamp: true


# Keep database from growing too large by purging
# No need to record some entities
# Must log automations to restore_state of automations on restart
recorder:
  purge_interval: 1
  purge_keep_days: 10
  exclude:
    entities:
      - sensor.time
      - sensor.rgb_state
      - sun.sun
      - input_boolean.heat0
      - input_boolean.heat1
      - device_tracker.joyce_ipad2
      - device_tracker.iphone
      - sensor.lr_random
      - sensor.br_random
      ## Several accumulators for which only the last value is required.
      - input_number.energy_accum
      - input_number.hourly_energy_accum
      - input_number.last_power
      - input_number.temp_diff_accum
      - input_number.hourly_temp_diff_accum
      - input_number.last_house_temp
      - input_number.last_house_humidity
      - input_number.last_gas
      ## No need to see history after debug
      - sensor.temp_diff
      - counter.fan_on_minutes
      - binary_sensor.updater
      - sensor.last_update_trigger
      - sensor.last_update_trigger_2
      - sensor.bssid
      - sensor.ssid
      - sensor.bssid_2
      - sensor.ssid_2
      - sensor.connection_type
      - sensor.battery_state
      - sensor.battery_level
      - sensor.battery_state_2
      - sensor.battery_level_2 
      - sensor.geocoded_location    
      - sensor.geocoded_location_2
      - sensor.connection_type
      - sensor.connection_type_2
      ## These are copied to input numbers for linear spline smoothing
      - sensor.mysensors_bme280_2_1
      - sensor.mysensors_bme280_2_2
      - sensor.mysensors_bme280_2_3
      - switch.watchdog
      - input_boolean.watchdog_delayed
      - sensor.soil_moisture_sensor_5_3
      
    domains:
      - zwave
      - device_tracker
      - automation
      - script

    ## Recommended to reduce database activity  
    event_types:
      - service_removed
      - service_executed
      - platform_discovered
      - homeassistant_start
      - homeassistant_stop      
      - feedreader
      - service_registered
      - call_service
      - component_loaded
      - logbook_entry
      - system_log_event
      - automation_triggered
      - script_started
      - timer_out_of_sync

# View only some events in logbook
# Depends on recorder settings.
logbook:
  include:
    entities:
      - climate.summer_fan
      - light.ge_12724_3way_dimmer_switch_level
      - lock.schlage_be469nxcen_touchscreen_deadbolt_locked
      - sensor.heat_state
      - sensor.back_lock_last_action
      - sensor.flood
      - binary_sensor.away
      - switch.back_irrigation
      - switch.deck_irrigation
      - switch.front_irrigation
      - switch.leviton_dz15s_1bz_decora_smart_switch_switch
      - switch.leviton_dzr151lz_binary_scene_switch_switch
      - sensor.medalert1_check


# View the history of only some components
# Depends on recorder settings.
history:
  exclude:
    domains:
      - automation
      - script
      - group
      - zwave
      - device_tracker
    entities:
      - binary_sensor.away
      - counter.fan_on_minute
      - device_tracker.joyce_ipad2
      - device_tracker.iphone
      - history_graph.rain_fall
      - input_boolean.vacation
      - input_boolean.watchdog
      - input_number.slider_home
      - input_number.slider_away
      - input_number.slider_delay_f
      - input_number.slider_delay_b
      - input_number.slider_delay_d
      - input_number.furnace_power
      - sensor.furnace_power_plot
      - input_number.slider_ac_home
      - input_number.slider_ac_away
      - input_number.power_test
      - input_number.box_gas
      - input_number.last_house_temp
      - input_number.last_house_humidity     
      - input_number.temperature
      - input_number.pressure
      - input_number.humidity
      - input_number.last_gas
      - input_datetime.lr_off_time
      - input_datetime.lr_off_time_random
      - input_datetime.br_on_time_random
      - input_datetime.br_off_time_random
      - input_datetime.heat_on_time
      - input_datetime.heat_off_time
      - lock.schlage_be469nxcen_touchscreen_deadbolt_locked
      - sensor.cooling
      - sensor.schlage_be469nxcen_touchscreen_deadbolt_access_control
      - sensor.schlage_be469nxcen_touchscreen_deadbolt_alarm_level
      - sensor.schlage_be469nxcen_touchscreen_deadbolt_alarm_type
      - sensor.schlage_be469nxcen_touchscreen_deadbolt_burglar
      - sensor.schlage_be469nxcen_touchscreen_deadbolt_power_management
      - sensor.schlage_be469nxcen_touchscreen_deadbolt_sourcenodeid
      - sensor.schlage_be469nxcen_touchscreen_deadbolt_system
      - sensor.lock_battery
      - sensor.yesterday_rainfall
      - sensor.precipitation
      - sensor.medalert1_check
      - input_number.temp_diff_accum
      - sensor.hour_diff
      - input_number.last_power
      - input_number.energy_accum
      - input_number.hourly_energy_accum
      - input_number.hourly_temp_diff_accum
      - input_number.last_house_temp
      - binary_sensor.updater
      - sensor.last_update_trigger
      - sensor.last_update_trigger_2
      - sensor.ssid
      - sensor.bssid
      - sensor.bssid_2
      - sensor.ssid_2
      - sensor.connection_type
      - sensor.battery_state
      - sensor.battery_level
      - sensor.battery_state_2
      - sensor.battery_level_2
      - sensor.geocoded_location    
      - sensor.geocoded_location_2
      - sensor.connection_type
      - sensor.connection_type_2
      - sensor.date
      - light.mqtt_json_light
      - sensor.air_quality_health_index
      - sensor.icon_code
      - sensor.iqa
      - switch.watchdog
      - input_boolean.watchdog_delayed
      - sensor.soil_moisture_sensor_4_1
      - sensor.soil_moisture_sensor_4_2
      - sensor.soil_moisture_sensor_4_3
      - sensor.soil_moisture_sensor_4_4
      - sensor.soil_moisture_sensor_5_1
      - sensor.soil_moisture_sensor_5_2
      - sensor.soil_moisture_sensor_5_3
      - sensor.soil_moisture_sensor_6_1
      - sensor.soil_moisture_sensor_6_2
      - sensor.soil_moisture_sensor_6_3
      - sensor.soil_moisture_sensor_6_4
      - sensor.ecolink_motion_detector_alarm_level
      - sensor.ecolink_motion_detector_alarm_type
      - sensor.ecolink_motion_detector_battery_level
      - sensor.ecolink_motion_detector_burglar
      - sensor.ecolink_motion_detector_power_management
      - sensor.ecolink_motion_detector_sourcenodeid

# Track the sun
sun:

# Keep alive repeats furnace ON or OFF message every 3 minutes
# Furnace Arduino will expect repeated furnace ON messages to keep the furnace relay ON.

climate:
  - platform: generic_thermostat
    name: House
    heater: switch.furnace
    target_sensor: sensor.house_temperature
    min_temp: 15
    max_temp: 25
    target_temp: !secret temperature_home
    precision: 0.1
    cold_tolerance: 0.3
    # Reduce overshoot on the hot side with MultiSensor2
    hot_tolerance: 0.1
    min_cycle_duration:
      seconds: 10
    keep_alive:
      minutes: 3
    initial_hvac_mode: "heat"

  - platform: generic_thermostat
    name: Summer Fan
    heater: switch.fan
    target_sensor: sensor.house_temperature
    min_temp: 22
    max_temp: 35
    target_temp: !secret temperature_fan
    precision: 0.1
    cold_tolerance: 0.3
    hot_tolerance: 0.3
    min_cycle_duration:
      seconds: 10
    ac_mode: true
    initial_hvac_mode: "cool"
    
  - platform: mqtt
    name: "Mitsubishi Heatpump"
    # Mode Definitions
    modes:
      - "off"
      - heat
      - dry
      - cool
      - fan_only
      - auto
    fan_modes:
      - AUTO
      - QUIET
      - "1"
      - "2"
      - "3"
      - "4"
    swing_modes:
      - AUTO
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
      - SWING
    # MQTT Status Topic Processing
    current_temperature_topic: "heatpump/status"
    current_temperature_template: "{{ value_json.roomTemperature }}"
    mode_state_topic: "heatpump"
    mode_state_template: >
      {% if value_json.power == "OFF" %}
        off
      {% elif value_json.mode == "FAN" %}
        fan_only
      {% else %}
        {{ value_json.mode|lower }}
      {% endif %}
    temperature_state_topic: "heatpump"
    temperature_state_template: "{{ value_json.temperature }}"
    fan_mode_state_topic: "heatpump"
    fan_mode_state_template: "{{ value_json.fan }}"
    swing_mode_state_topic: "heatpump"
    swing_mode_state_template: "{{ value_json.vane }}"    
    action_topic: "heatpump"
    action_template: >
      {% if value_json.power == "ON" %}
        cooling
      {% else %}
        idle
      {% endif %}
    # MQTT Command Topics
    # Additional automation is required to process HQTT HVAC topics into a single set topic
    # with a json payload.
    mode_command_topic: "heatpump/_set/mode"
    temperature_command_topic: "heatpump/_set/temperature"
    fan_mode_command_topic: "heatpump/_set/fan"
    swing_mode_command_topic: "heatpump/_set/vane"
    
# Used in automations to detect when I leave and come home again.  'on' = away
# Add special condition for Oliver since he sometimes locks using a key code
# Consolates input_boolean.vacation to override when on vacation.
binary_sensor:
  - platform: template
    sensors:
      away:
        value_template: >
          {{ is_state("sensor.back_lock_last_action", "Locked: Outside Keypad")
          or is_state("sensor.back_lock_last_action", "Locked: Oliver")
          or is_state("input_boolean.vacation", "on") }}
        friendly_name: 'I am away'

counter:
  fan_on_minutes:
    icon: mdi:fan

input_boolean:
  vacation:
    name: "ON Vacation"
    icon: mdi:car

  watchdog:
    name: "Watchdog Alarm Override"
    initial: off
    icon: mdi:lock
    
  watchdog_delayed:
    name: "Watchdog Delayed"
    initial: off

  heat0:    
    name: "Heat State 0"
    initial: off

  heat1:    
    name: "Heat State 1"
    initial: off

input_number:
  slider_home:
    name: Home
    #initial: 21
    min: 18
    max: 25
    step: 0.5
    icon: mdi:target
  slider_away:
    name: Away
    #initial: 18
    min: 16
    max: 20
    step: 0.5
    icon: mdi:target
  slider_delay_f:
    name: Front Duration
    min: 5
    max: 29
    step: 1.0
    icon: mdi:target
  slider_delay_b:
    name: Back Duration
    min: 5
    max: 29
    step: 1.0
    icon: mdi:target
  slider_delay_d:
    name: Deck Duration
    min: 5
    max: 29
    step: 1.0
    icon: mdi:target
  furnace_power:
    name: Furnace Power
    min: 0
    max: 50
    step: 0.1
    unit_of_measurement: 'kW'
  slider_ac_home:
    name: AC Home
    #initial: 21
    min: 20
    max: 25
    step: 0.5
    icon: mdi:target
  slider_ac_away:
    name: AC Away
    #initial: 18
    min: 20
    max: 30
    step: 0.5
    icon: mdi:target
  box_gas:
    name: Base Gas Resistance
    min: 100
    max: 2000
    step: 10
    mode: box
#stores the last power level when outside of current window.
  last_power:
    min: 0
    max: 100
    step: 0.1
    unit_of_measurement: 'kW'
    mode: box
# Accumulates temperature difference values over an hour.
# Sum at end of hour is copied to sensor.hour_diff for graphing.
  temp_diff_accum:
    min: 0
    max: 1000
    step: 0.1
    mode: box
# Accumulates hourly temperature difference values.
# Sum at the end of the day is copied to sensor.daily_temp_diff for graphing.
  hourly_temp_diff_accum:
    min: 0
    max: 1000
    step: 0.1
    mode: box
# Accumulates energy use over an hour.
# Sum at end of hour is copied to sensor.hourly_energy for graphing.
  energy_accum:
    min: 0
    max: 1000
    step: 0.1
    mode: box    
# Accumulates hourly energy values.
# Sum at the end of the day is copied to sensor.daily_energy for graphing.
  hourly_energy_accum:
    min: 0
    max: 1000
    step: 0.1
    mode: box
# Save for sensor.house_temperature restore after HA restart
  last_house_temp:
    min: 0
    max: 100
    step: 0.1
    mode: box
# Save last sensor.multisensor2_humidity for HA restart
  last_house_humidity:
    min: 0
    max: 100
    step: 1
    mode: box
# Save last sensor.multisensor2_gasavg for HA restart
  last_gas:
    min: 0
    max: 5000
    step: 1
    mode: box
  temperature:
    min: -20
    max: 50
    step: 0.1
    mode: box
  pressure:
    min: 800
    max: 1200
    step: 0.1
    mode: box
  humidity:
    min: 0
    max: 100
    step: 1
    mode: box
  hour_diff:
    min: -20
    max: 100
    step: 0.1
    mode: box
  hourly_energy:
    min: 0
    max: 100
    step: 0.1
    mode: box
  daily_energy:
    min: 0
    max: 100
    step: 0.1
    mode: box
  daily_temp_diff:
    min: -20
    max: 100
    step: 0.1
    mode: box   
 # Used to generate at test pattern to power
  # power_test:
    # name: Power Test
    # initial: 0
    # min: 0
    # max: 50
    # step: 1    

input_datetime:
  lr_off_time:
    name: Living Room Light OFF
    has_date: false
    has_time: true

  lr_off_time_random:
    name: Living Room Light Random OFF
    has_date: false
    has_time: true

  br_on_time_random:
    name: Bed Room Light Random ON
    has_date: false
    has_time: true

  br_off_time_random:
    name: Bed Room Light Random OFF
    has_date: false
    has_time: true
    
  heat_on_time:
    name: Heat ON time
    has_date: false
    has_time: true

  heat_off_time:
    name: Heat OFF time
    has_date: false
    has_time: true

# Replaced by Python energy.py script    
# utility_meter:
  # furnace_hourly:
    # source: sensor.sensor_furnace_power_integral
    # cycle: hourly
  # furnace_daily:
    # source: sensor.sensor_furnace_power_integral
    # cycle: daily
 

#This worked with a Google Home Mini to control all switches and light using a voice command
#Joyce considered this an invasion of privacy so I had to disconnect the service.
#I changed the HA password after disconnection.
# google_assistant:
  # project_id: graham-bb666
  # client_id: WRWcrvxwzflm4cihLtNGM29XvUfNNuz4Xr2fbdgRMa0vBoUoGAZrnYEKwByuYBQMpaQ7E4OSTJw8pE1e
  # access_token: JdC6XKyrVDi7tLCTmY1WDvmgs59o5cScdKk7oMu5j1QIED6mHxrDRKY978h26qqsgnOGKjACCQruEhEc
  # agent_user_id: gb53smith@gmail.com
  # api_key: AIzaSyAWxbX5diYHEskrc3pHEcNR-DH0UVocRNk
  # exposed_domains:
    # - switch
    # - light
    
# MultiSensor2 Support
# ms2 added to prevent possible conflict with Z-wave light.  It is needed.
light ms2:
  - platform: mqtt
    schema: json
    command_topic: "/home/ms2/l"
    state_topic: "/home/ms2/lc"
    rgb: true
    retain: true

# Include other files to better organize code
group: !include groups.yaml
automation pre45: !include automations.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
script: !include scripts.yaml
