homeassistant:
  customize: !include customize.yaml

default_config:
# New line to test git
# #Includes
# #Show links to resources in log and frontend
# #introduction:
# system_health:
# zeroconf:
# # See Helpers in UI
# input_text:
# #Running NGINX on another PI 4 so I can share my IP address with PrivateBook
# # Enables the frontend
# frontend:
  # #javascript_version: es5
# # Enables configuration UI
# config:
# # Checks for available updates
# updater:
# #Replace discovery with hassio
# hassio:
# # Discover some devices automatically
# discovery:
  # ignore:
    # - apple_tv
# # Track the sun
# sun:
# #Enable IOS App, Home Assistant Companion
# mobile_app:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.90

#websocket_api:

#Try fixed IP address to fix update warnings.  Moved to UI.
#samsungtv:
#  - host: 192.168.1.74
  
#esphome:

python_script:

#This set the severity of notices in the log file
#Can be set to "info" for more detail or "debug" for certain components
logger:
  default: warning
  # Ignore rainforest errors and warnings as it reboots daily.
  logs:
    homeassistant.components.rainforest_eagle.data: critical
    homeassistant.components.websocket_api.http.connection: error
  # logs:
    # homeassistant.components.python_scripts: debug
    # homeassistant.components.sensor.time: error

# #For Mysensors debug only
# logger:
  # default: info
  # logs:
    # homeassistant.components.mysensors: debug
    # mysensors: debug

# # Send SMS if burglar alarm triggered
# twilio:
  # account_sid: !secret account_sid
  # auth_token: !secret auth_token

# notify:
  # # - name: Burglar Alarm SMS
    # # platform: twilio_sms
    # # from_number: !secret from_number
  # - name: energy_notify
    # platform: file
    # filename: hourly_energy.csv
    # timestamp: true

# Keep database from growing too large by purging
# No need to record some entities
# Must log automations to restore_state of automations on restart
recorder:
  auto_purge: true
  auto_repack: true
  purge_keep_days: 10
  exclude:
    entities:
      - sensor.time
      - sensor.rgb_state
      - sun.sun
      - input_boolean.heat0
      - input_boolean.heat1
      - device_tracker.joyce_ipad2
      - device_tracker.iphone
      - sensor.lr_random
      - sensor.br_random
      ## Several accumulators for which only the last value is required.
      #- input_number.energy_accum
      - input_number.hourly_energy_accum
      #- input_number.last_power
      - input_number.temp_diff_accum
      - input_number.hourly_temp_diff_accum
      #GBS- input_number.last_house_temp
      - input_number.last_house_humidity
      ## calibration settings
      - input_number.soil_dry_1
      - input_number.soil_wet_1
      - input_number.soil_dry_2
      - input_number.soil_wet_2
      ## plant fan limits
      - input_number.max_humidity
      - input_datetime.plant_light_off_time
      - input_datetime.plant_light_on_time
      ## No need to see history after debug
      #- sensor.temp_diff
      - counter.fan_on_minutes
      - counter.brita_days
      - binary_sensor.updater
      - sensor.soil_moisture_sensor_5_3
      # iPhone entities not used
      - sensor.iphone_battery_level
      - sensor.iphone_battery_state
      - sensor.iphone_bssid
      - sensor.iphone_connection_type
      - sensor.iphone_last_update_trigger
      - sensor.iphone_sim_1
      - sensor.iphone_ssid
      - sensor.iphone_storage
      # iPad entities not used
      - sensor.joyce_ipad2_battery_level
      - sensor.joyce_ipad2_battery_state
      - sensor.joyce_ipad2_bssid
      - sensor.joyce_ipad2_connection_type
      - sensor.joyce_ipad2_last_update_trigger
      - sensor.joyce_ipad2_ssid
      - sensor.joyce_ipad2_storage
      #- sensor.z_wave_motion_sensor_battery_level
      - input_boolean.plant_automation
      # UPS states not worth saving
      - sensor.myups_battery_runtime
      - sensor.myups_battery_voltage
      - sensor.myups_beeper_status
      - sensor.myups_input_voltage
      - sensor.myups_load
      #Energy Meter. Only need last value
      - sensor.eagle_200_total_meter_energy_delivered
      - sensor.eagle_200_net_meter_energy_delivered_minus_received
      - sensor.eagle_200_total_meter_energy_received
      - sensor.meter_price
      - input_number.hydro_meter_last_hour
      - input_number.hydro_meter_last_day
      - input_number.hepa_hours
      #MS3
      - sensor.multisensor_gen3_ms3_gas_resistance
      - sensor.ms3_rssi
      - sensor.ms3_breath_voc_equivalent
      - sensor.ms3_co2_equivalent

    domains:
      - zwave
      - device_tracker
      - automation
      - script
      - group

    ## Recommended to reduce database activity
    event_types:
      - service_removed
      - service_executed
      - platform_discovered
      - homeassistant_start
      - homeassistant_stop
      - feedreader
      - service_registered
      - call_service
      - component_loaded
      - logbook_entry
      - system_log_event
      - automation_triggered
      - script_started
      - timer_out_of_sync

# View only some events in logbook
# Depends on recorder settings.
# logbook:
  # include:
    # entities:
      # - climate.summer_fan
      # - light.ge_12724_3way_dimmer_switch_level
      # - lock.schlage_be469nxcen_touchscreen_deadbolt_locked
      # - sensor.heat_state
      # - sensor.flood
      # - binary_sensor.away
      # - switch.back_irrigation
      # - switch.deck_irrigation
      # - switch.front_irrigation
      # - switch.scene_capable_switch_on_off
      # - switch.leviton_dzr151lz_binary_scene_switch_switch
      # - sensor.widevane
      # Test only
      # - input_number.power_test
      # - input_number.energy_accum
      # - input_number.hourly_energy

# View the history of only some components
# Depends on recorder settings.
# history:
  # include:
    # entities:
      # - sensor.date
      # - lock.schlage_be469nxcen_touchscreen_deadbolt_locked
      # - binary_sensor.away
      # - binary_sensor.ecolink_motion_detector_sensor
      # - switch.scene_capable_switch_on_off
      # - switch.back_irrigation
      # - switch.deck_irrigation
      # - switch.front_irrigation
      # - switch.furnace
      # - switch.fan
      # - sensor.flood
      # - sensor.house_temperature
      # - sensor.eagle_200_meter_power_demand

# Keep alive repeats furnace ON or OFF message every 3 minutes
# Furnace Arduino will expect repeated furnace ON messages to keep the furnace relay ON.

climate:
  - platform: generic_thermostat
    name: House
    heater: switch.furnace
    target_sensor: sensor.house_temperature
    min_temp: 15
    max_temp: 25
    precision: 0.1
    cold_tolerance: 0.3
    hot_tolerance: 0.3
    min_cycle_duration:
      seconds: 10
    keep_alive:
      minutes: 3
    initial_hvac_mode: "heat"

  - platform: generic_thermostat
    name: Summer Fan
    heater: switch.fan
    target_sensor: sensor.house_temperature
    min_temp: 22
    max_temp: 35
    precision: 0.1
    cold_tolerance: 0.3
    hot_tolerance: 0.3
    min_cycle_duration:
      seconds: 10
    ac_mode: true
    initial_hvac_mode: "cool"
    
  - platform: generic_thermostat
    name: Soil Heater
    heater: switch.plant_heater
    target_sensor: sensor.plants_soil_temperature
    min_temp: 10
    max_temp: 28
    precision: 0.1
    cold_tolerance: 0.3
    hot_tolerance: 0.1
    # Prevent heater stuck ON
    keep_alive:
      minutes: 5
    initial_hvac_mode: "heat"  


# Used in automations to detect when I leave and come home again.  'on' = away
# Add special condition for Oliver since he sometimes locks using a key code
# input_boolean.vacation is used to force "I am away" to "on" if door lock fails.
binary_sensor:
  - platform: template
    sensors:
      away:
        value_template: >
          {{ is_state("input_text.lock_last_action", "Locked by Keypad")
          or is_state("input_text.lock_last_action", "Locked by Oliver")
          or is_state("input_boolean.vacation", "on") }}
        friendly_name: "I am away"

# Monitor MultiSensor2 that measures house temperature.
# IP address reserved using the DCHP setting on my router
# Moved to 106 since extender assigns IP addresses starting at 100
  - platform: ping 
    host: 192.168.1.108
    name: "ping ms3"
    
counter:
  fan_on_minutes:
    icon: mdi:fan
  brita_days:
    icon: mdi:glass-water

# Used to set wide vane position every time the heat pump is turned ON as it
# seems to revert to "<<" for no reason.
input_select:
  widevane:
    name: Wide Vane Setting
    options:
       -  "<<"
       -  "<"
       -  "|"
       -  ">"
       -  ">>"
       -  "SWING"
    icon: mdi:air-filter 
    
# Include other files to better organize code
input_number: !include input_number.yaml
input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml
group: !include groups.yaml
automation: !include automations.yaml
sensor: !include sensors.yaml
script: !include scripts.yaml
mqtt: !include mqtt.yaml
template: !include template.yaml
command_line: !include command_line.yaml
