#Sensors
- platform: random
  name: lr_random
  minimum: 0
  maximum: 30
  scan_interval: 3600

- platform: random
  name: br_random
  minimum: 0
  maximum: 10
  scan_interval: 3600

- platform: time_date
  display_options:
    - "time"
    - "date"

# - platform: command_line
  # name: Yesterday Rainfall
  # unit_of_measurement: "mm"
  # scan_interval: 10800
  # command: "python3 /config/getrain.py"

## Filter in HA instead of at IOT device
# - platform: filter
  # name: "Average Gas Resistance"
  # entity_id: sensor.multisensor_gen3_ms3_gas_resistance
  # filters:
    # - filter: time_simple_moving_average
      # window_size: "02:40"
      # precision: 0

#- platform: websocket_api

- platform: filter
  name: "Average Outdoor Temperature"
  entity_id: sensor.outdoor_temp
  filters:
    - filter: time_simple_moving_average
      window_size: "24:00"
      precision: 0.1