#Sensors
- platform: random
  name: lr_random
  minimum: 0
  maximum: 30
  scan_interval: 3600

- platform: random
  name: br_random
  minimum: 0
  maximum: 10
  scan_interval: 3600

- platform: time_date
  display_options:
    - "time"
    - "date"

- platform: command_line
  name: Yesterday Rainfall
  unit_of_measurement: "mm"
  scan_interval: 10800
  command: "python3 /config/getrain.py"

