# For Relay4 Arduino Project
- platform: mqtt
  name: "Back Irrigation"
  state_topic: "/home/irrigation/zoneConfirm1"
  command_topic: "/home/irrigation/zone1"
  retain: False

- platform: mqtt
  name: "Front Irrigation"
  state_topic: "/home/irrigation/zoneConfirm2"
  command_topic: "/home/irrigation/zone2"
  retain: False

- platform: mqtt
  name: "Deck Irrigation"
  state_topic: "/home/irrigation/zoneConfirm3"
  command_topic: "/home/irrigation/zone3"
  retain: False

# For Furnace_Controller Arduino Project
- platform: mqtt
  name: "Furnace"
  state_topic: "/home/furnace/heat/confirm"
  command_topic: "/home/furnace/heat"
  retain: False

- platform: mqtt
  name: "Fan"
  state_topic: "/home/furnace/fan/confirm"
  command_topic: "/home/furnace/fan"
  retain: False

# Multisensor2 support
- platform: mqtt
  name: "Watchdog"
  state_topic: "/home/ms2/wc"
  command_topic: "/home/ms2/w"
  payload_on: '{"s":"ON"}'
  payload_off: '{"s":"OFF"}'
  state_on: "ON"
  state_off: "OFF"
  value_template: "{{ value_json.s }}"
  retain: False
  
# For Plants Support
- platform: mqtt
  name: "Plant1"
  state_topic: "/home/plants/plant1/confirm"
  command_topic: "/home/plants/plant1"
  retain: False

- platform: mqtt
  name: "Plant2"
  state_topic: "/home/plants/plant2/confirm"
  command_topic: "/home/plants/plant2"
  retain: False

- platform: mqtt
  name: "Plant3"
  state_topic: "/home/plants/plant3/confirm"
  command_topic: "/home/plants/plant3"
  retain: False
