title: Rose Cottage
views:
  - badges: []
    cards:
      - entities:
          - entity: switch.leviton_dzr151lz_binary_scene_switch_switch
          - entity: light.ge_12724_3way_dimmer_switch_level
          - entity: switch.leviton_dz15s_1bz_decora_smart_switch_switch
        show_header_toggle: false
        title: Lights
        type: entities
      - entities:
          - entity: input_boolean.vacation
          - entity: climate.house
          - entity: input_number.slider_home
          - entity: input_number.slider_away
          - entity: climate.mitsubishi_heatpump
          - entity: input_number.slider_ac_home
          - entity: input_number.slider_ac_away
          - entity: sensor.multisensor2_humidity
          - entity: sensor.iaq
        show_header_toggle: false
        title: Temperature Control
        type: entities
      - entities:
          - entity: lock.schlage_be469nxcen_touchscreen_deadbolt_locked
          - entity: sensor.back_lock_last_action
        show_header_toggle: false
        title: Back Door Lock
        type: entities
      - entities:
          - entity: sensor.mysensors_bme280_2_2
          - entity: sensor.mysensors_bme280_2_1
          - entity: sensor.mysensors_bme280_2_3
        show_header_toggle: false
        title: Outdoor Conditions
        type: entities
      - entities:
          - sensor.remote_temperature
          - sensor.remote_humidity
        show_header_toggle: false
        title: Wine Cellar
        type: entities
      - entities:
          - entity: sensor.flood
          - entity: sensor.medalert1_check
        show_header_toggle: false
        title: Alarms
        type: entities
      - entity: sensor.soil_moisture_sensor_4_1
        max: 100
        min: 0
        name: Plant Soil Moisture
        severity:
          green: 50
          red: 10
          yellow: 40
        theme: default
        type: gauge
    icon: 'mdi:home'
    path: default_view
    theme: default
    title: default_view
  - badges: null
    cards:
      - entities:
          - entity: automation.back_irrigation
          - entity: input_number.slider_delay_b
          - entity: automation.front_irrigation
          - entity: input_number.slider_delay_f
          - entity: automation.deck_irrigation
          - entity: input_number.slider_delay_d
        show_header_toggle: false
        title: Irrigation Automation
        type: entities
      - entities:
          - input_datetime.lr_off_time
        show_header_toggle: false
        title: Light Automation
        type: entities
      - entities:
          - entity: input_datetime.heat_on_time
          - entity: input_datetime.heat_off_time
          - entity: counter.fan_on_minutes
          - entity: input_boolean.fan_reset
          - entity: automation.hvac
        show_header_toggle: false
        title: Heat Automation
        type: entities
      - entities:
          - entity: switch.furnace
          - entity: switch.fan
          - entity: switch.away
          - entity: switch.back_irrigation
          - entity: switch.front_irrigation
          - entity: switch.deck_irrigation
          - entity: switch.watchdog
          - entity: input_boolean.watchdog
        show_header_toggle: false
        title: Switch
        type: entities
      - entities:
          - entity: sensor.multisensor2_gas
          - entity: sensor.multisensor2_gasavg
          - entity: input_number.box_gas
          - entity: sensor.iaq
          - entity: sensor.multisensor2_pressure
          - entity: sensor.multisensor2_humidity
          - entity: sensor.multisensor2_temperature
          - entity: sensor.multisensor2_rssi
        show_header_toggle: false
        title: MultiSensor 2
        type: entities
      - entities:
          - entity: sensor.mysensors_bme280_2_4
          - entity: sensor.soil_moisture_sensor_4_2
          - entity: sensor.lock_battery
        show_header_toggle: false
        title: Remote Battery Voltages
        type: entities
      - entity: light.mqtt_json_light
        name: Heat State
        type: light
    path: back_end
    title: Back End
  - badges: []
    cards:
      - entities:
          - sensor.hour_diff
          - sensor.furnace_power
          - sensor.hourly_energy
        hours_to_show: 24
        refresh_interval: 10
        show_header_toggle: false
        theme: default
        title: Day House Energy Use
        type: history-graph
      - entities:
          - sensor.date
          - sensor.hour_diff
          - sensor.daily_energy
          - sensor.daily_temp_diff
        hours_to_show: 168
        refresh_interval: 300
        show_header_toggle: false
        theme: default
        title: Week House Energy Use
        type: history-graph
      - entities:
          - sensor.date
          - sensor.precipitation
          - climate.mitsubishi_heatpump
        hours_to_show: 168
        refresh_interval: 0
        show_header_toggle: false
        theme: default
        title: Week Rainfall History
        type: history-graph
      - entities:
          - climate.house
        hours_to_show: 168
        type: history-graph
    panel: false
    title: GRAPHS
  - badges: []
    cards:
      - entities:
          - sensor.condition
          - sensor.forecast
          - sensor.temperature_2
          - sensor.humidity_2
          - sensor.pressure
          - sensor.tendency
          - sensor.high_temperature
          - sensor.low_temperature
          - sensor.uv_index
          - sensor.visibility
          - sensor.wind_speed
          - sensor.wind_direction
        show_header_toggle: false
        title: Vancouver Weather
        type: entities
    path: weather
    title: WEATHER
