title: Rose Cottage
views:
  - badges: []
    cards:
      - entities:
          - entity: switch.leviton_dzr151lz_binary_scene_switch_switch
          - entity: light.ge_12724_3way_dimmer_switch_level
          - entity: switch.leviton_dz15s_1bz_decora_smart_switch_switch
        show_header_toggle: false
        title: Lights
        type: entities
      - entities:
          - lock.schlage_be469nxcen_touchscreen_deadbolt_locked
          - sensor.back_lock_last_action
          - sensor.lock_battery
        show_header_toggle: false
        title: Back Door Lock
        type: entities
      - entities:
          - entity: input_boolean.vacation
          - entity: climate.house
          - entity: input_number.slider_home
          - entity: input_number.slider_away
          - entity: sensor.heat_state
        show_header_toggle: false
        title: Temperature Control
        type: entities
      - entities:
          - sensor.remote_temperature
          - sensor.remote_humidity
        show_header_toggle: false
        title: Wine Cellar
        type: entities
      - entities:
          - input_boolean.watchdog
          - sensor.flood
        show_header_toggle: false
        title: Alarms
        type: entities
      - entities:
          - sensor.mysensors_bme280_2_2
          - sensor.mysensors_bme280_2_1
          - sensor.mysensors_bme280_2_3
          - sensor.mysensors_bme280_2_4
        show_header_toggle: false
        title: Outdoor Conditions
        type: entities
    icon: 'mdi:home'
    path: default_view
    title: default_view
  - badges:
      - sensor.humidity
      - sensor.yesterday_rainfall
      - sensor.medalert1_check
    cards:
      - entities:
          - automation.back_irrigation
          - automation.front_irrigation
          - automation.deck_irrigation
          - input_number.slider_delay
        show_header_toggle: true
        title: Irrigation Automation
        type: entities
      - entities:
          - input_datetime.lr_off_time
        show_header_toggle: false
        title: Light Automation
        type: entities
      - entities:
          - entity: input_datetime.heat_on_time
          - entity: input_datetime.heat_off_time
          - entity: counter.fan_on_minutes
          - entity: input_boolean.fan_reset
        show_header_toggle: false
        title: Heat Automation
        type: entities
      - entities:
          - switch.furnace
          - switch.fan
          - switch.away
          - switch.heat0
          - switch.heat1
          - switch.back_irrigation
          - switch.front_irrigation
          - switch.deck_irrigation
          - switch.watchdog
        show_header_toggle: false
        title: Switch
        type: entities
    path: back_end
    title: Back End
  - badges: []
    cards:
      - entities:
          - sensor.hour_diff
          - sensor.furnace_power
          - sensor.hourly_energy
        hours_to_show: 24
        refresh_interval: 10
        show_header_toggle: false
        theme: default
        title: Day House Energy Use
        type: history-graph
      - entities:
          - sensor.date
          - sensor.hour_diff
          - sensor.daily_energy
          - sensor.daily_temp_diff
        hours_to_show: 168
        refresh_interval: 300
        show_header_toggle: false
        theme: default
        title: Week House Energy Use
        type: history-graph
      - entities:
          - sensor.date
          - sensor.yesterday_rainfall
        hours_to_show: 168
        refresh_interval: 0
        show_header_toggle: false
        theme: default
        title: Week Rainfall History
        type: history-graph
    panel: false
    title: GRAPHS
