esphome:
  name: ${node_name}
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "GreenMountain"
  password: !secret wifi_password

captive_portal:
 
# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret ota_password

ota:
  password: !secret ota_password