logger:
  level: DEBUG

substitutions:
  node_name: heatpump
  
  
esphome:
  name: ${node_name}
  platform: ESP8266
  board: nodemcuv2
  includes:
    - my_heatpump.h

wifi:
  ssid: "GreenMountain"
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.110
    gateway: 192.168.1.254
    subnet: 255.255.255.0

# Enable Home Assistant API

#api:
#  password: !secret ota_password
#  encryption:
#    key: !secret api_encryption_key

ota:
  password: !secret ota_password

mqtt:
  topic_prefix: heatpump
  discovery: false
  broker: 192.168.1.65
  username: gbsmith
  password: !secret mqtt_password
  discovery_prefix: homeassistant
  

binary_sensor:
  - platform: gpio
    name: "Heatpump button"
    pin:
      number: D7
      mode: INPUT_PULLUP
      inverted: True

sensor:
  # WiFi Signal sensor.
  - platform: wifi_signal
    name: ${node_name} WiFi Signal
    update_interval: 60s


custom_component:
  - lambda: |-
      auto my_custom = new MyCustomComponent();
      return {my_custom};  


light:
  - platform: binary
    name: "Heat Pump LED"
    id: light1
    output: output1
#  - platform: binary
#    name: "Heat Pump Blue LED"
#    id: light2
#    output: output2

output:
  - platform: gpio
    pin: D6
    inverted: True
    id: output1
#  - platform: gpio
#    pin: D4
#    inverted: True
#    id: output2