esphome:
  name: wayne
  friendly_name: Wayne

esp8266:
  board: d1_mini
  #restore_from_flash: True

# Enable logging
logger:
  level: DEBUG

#Use iPhone/iPad to connect to Wayne1 using password
#Works but does not provide an user iterface to set times
#wifi:
#  ap:
#    ssid: "Wayne1"
#    password: "BCIT1973"
#   ap_timeout: 1s

#web_server:
#  local: true
wifi:
  ssid: "GreenMountain"
  password: !secret wifi_password
  # Optional manual IP
  manual_ip:
    static_ip: 192.168.1.107
    gateway: 192.168.1.254
    subnet: 255.255.255.0

ota:
  password: !secret ota_password

# Enable Home Assistant API
api:
  encryption:
   key: !secret api_encryption_key

  services:
    - service: start_full_cycle
      then:
        - sprinkler.start_full_cycle: sprinkler_ctrlr

switch:
  - platform: gpio
    name: "Valve1"
    pin: D6
    id: id_value1
  - platform: gpio
    name: "Valve2"
    pin: D7
    id: id_value2
#time:
# - platform: sntp
#    on_time:
#      # Every minute
#      - seconds: 0
#        minutes: /1
#        then:
#          - switch.toggle: id_value1

sprinkler:
  - id: sprinkler_ctrlr
    main_switch: "Sprinklers"
    auto_advance_switch: "Sprinklers Auto Advance"
    valves:
      - valve_switch: "Front Lawn"
        enable_switch: "Enable Front Lawn"
        run_duration_number:
          name: "Zone 1 Duration"
          initial_value: 10
          unit_of_measurement: min
        valve_switch_id: id_value1
      - valve_switch: "Back Lawn"
        enable_switch: "Enable Back Lawn"
        run_duration_number:
          name: "Zone 2 Duration"
          initial_value: 10
          unit_of_measurement: min
        valve_switch_id: id_value2